#!/usr/bin/python

import numpy as np


def format_raw_data(raw_data):
    data, labels = raw_data[0], raw_data[1]


def load_data(path: str, load_mode=0):
    """
    Read the npy file in a directory and restore it to a numpy array,
    including the label return of the image data

    :param path: Directory where npy files are stored The file should be generated by easy-image,
    which means that the directory contains three files: "train.npy", "valid.npy", and "test.npy".

    :param load_mode: Specify which data to load:
        0: load train and validation data, return (train_data, train_labels, valid_data, valid_labels)
        1: load only train data, return (train_data, train_labels)
        2: load only test data, return (test_data, test_labels)
        -1: load all data, return (train_data, train_labels, valid_data, valid_labels,
                                  test_data, test_labels)

    :return: see load_mode
    """
    if load_mode not in list(range(3)):
        raise ValueError('load_mode should be 0, 1, 2 or 3.Found', str(load_mode))

    train_data, train_labels = None, None
    valid_data, valid_labels = None, None
    test_data, test_labels = None, None

    # if load_mode
